# srcs/docker-compose.yml
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:42
    restart: always
    env_file:
      - .env
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:42
    restart: always
    env_file:
      - .env
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:42
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./wordpress_data:/var/www/html:ro
    networks:
      - inception

networks:
  inception:
    driver: bridge
